export interface ExamQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
}

export const COMPREHENSIVE_50_QUESTIONS: ExamQuestion[] = [
  {
    id: 'q1',
    question: 'What is the primary moral foundation of professional policing under the PNP Code of Conduct?',
    options: ['Command hierarchy', 'Ethical integrity and public trust', 'Tactical superiority', 'Administrative speed'],
    correctAnswer: 1,
  },
  {
    id: 'q2',
    question: 'Which law regulates the Code of Conduct and Ethical Standards for Public Officials and Employees in the Philippines?',
    options: ['Republic Act 3815', 'Republic Act 6713', 'Republic Act 9165', 'Republic Act 10175'],
    correctAnswer: 1,
  },
  {
    id: 'q3',
    question: 'What is the required passing percentage threshold for the PNP Course Final Exam?',
    options: ['60%', '70%', '75%', '80%'],
    correctAnswer: 3,
  },
  {
    id: 'q4',
    question: 'How many questions must an officer answer correctly to pass the 50-question PNP Final Exam with an 80% score?',
    options: ['35 questions', '38 questions', '40 questions', '45 questions'],
    correctAnswer: 2,
  },
  {
    id: 'q5',
    question: 'What is the FIRST step in the PNP Ethical Decision-Making Framework when encountering an operational dilemma?',
    options: ['Issue an immediate public announcement', 'Identify the issue and core ethical conflict', 'Consult social media', 'Transfer responsibility to subordinates'],
    correctAnswer: 1,
  },
  {
    id: 'q6',
    question: 'What does the principle of Transparency require from law enforcement officers?',
    options: ['Sharing classified operation secrets publicly', 'Accurate, truthful, and honest incident recording', 'Altering logs to avoid bad publicity', 'Concealing evidence from official inquiries'],
    correctAnswer: 1,
  },
  {
    id: 'q7',
    question: 'Under Republic Act 6713, public officials are strictly prohibited from accepting:',
    options: ['Standard salaries', 'Gifts or gratuities influenced by official duties', 'Official commendations', 'Government-issued gear'],
    correctAnswer: 1,
  },
  {
    id: 'q8',
    question: 'What is the mandatory duty of a police officer who witnesses a fellow officer using unauthorized excessive force?',
    options: ['Ignore the situation', 'Intervene immediately and report to authorities', 'Join in the excessive force', 'Delete video evidence'],
    correctAnswer: 1,
  },
  {
    id: 'q9',
    question: 'Which PNP office is responsible for conducting administrative investigations into officer misconduct?',
    options: ['Traffic Management Group', 'Internal Affairs Service (IAS)', 'Communications Office', 'Finance Service'],
    correctAnswer: 1,
  },
  {
    id: 'q10',
    question: 'What core value emphasizes unwavering commitment to truth and honesty in policing?',
    options: ['Integrity', 'Impartiality', 'Proficiency', 'Punctuality'],
    correctAnswer: 0,
  },
  {
    id: 'q11',
    question: 'When conducting a warrantless arrest under lawful circumstances, officers must immediately:',
    options: ['Inform the suspect of their constitutional rights (Miranda Warning)', 'Interrogate without legal counsel', 'Detain indefinitely', 'Confiscate personal property without inventory'],
    correctAnswer: 0,
  },
  {
    id: 'q12',
    question: 'What principle dictates that force should only be used when strictly necessary and proportional to the threat?',
    options: ['Principle of Maximum Suppression', 'Principle of Necessity and Proportionality', 'Principle of Absolute Discretion', 'Principle of Retaliation'],
    correctAnswer: 1,
  },
  {
    id: 'q13',
    question: 'What is the primary objective of Community-Oriented Policing System (COPS)?',
    options: ['Building collaborative partnerships with citizens to prevent crime', 'Replacing formal court procedures', 'Increasing traffic fines', 'Conducting secretive surveillance'],
    correctAnswer: 0,
  },
  {
    id: 'q14',
    question: 'Which document outlines the standard operational rules for PNP officers during checkpoints and arrests?',
    options: ['PNP Operational Procedures (POP) Manual', 'Civil Code of the Philippines', 'Labor Code', 'Local Ordinance Index'],
    correctAnswer: 0,
  },
  {
    id: 'q15',
    question: 'Officers using AI tools for report generation must ensure that data processed complies with:',
    options: ['Data Privacy Act of 2012 (R.A. 10173)', 'E-Commerce Act only', 'Foreign data laws', 'Unregulated public domain policies'],
    correctAnswer: 0,
  },
  {
    id: 'q16',
    question: 'What does "Chain of Custody" refer to in criminal evidence handling?',
    options: ['The sequence of police ranks on duty', 'The unbroken documentation showing seizure, custody, control, and transfer of evidence', 'The physical handcuffs used during arrest', 'The budget allocation chain'],
    correctAnswer: 1,
  },
  {
    id: 'q17',
    question: 'How should an officer handle confidential information obtained during official investigations?',
    options: ['Share it on personal social media accounts', 'Protect it strictly in accordance with security protocols', 'Sell it to news outlets', 'Discuss it freely at public venues'],
    correctAnswer: 1,
  },
  {
    id: 'q18',
    question: 'What is the consequence of failing to log evidence accurately in the police blotter?',
    options: ['Evidence compromise and potential dismissal of criminal charges', 'Automatic promotion', 'No legal impact', 'Award for speed'],
    correctAnswer: 0,
  },
  {
    id: 'q19',
    question: 'What constitutional right protects individuals from arbitrary search and seizure without a valid warrant?',
    options: ['Bill of Rights Section 2', 'Bill of Rights Section 12', 'Article II Section 1', 'Article VII Section 4'],
    correctAnswer: 0,
  },
  {
    id: 'q20',
    question: 'In crisis management, what is the primary goal of police de-escalation tactics?',
    options: ['To resolve conflicts peacefully without physical force whenever feasible', 'To provoke verbal arguments', 'To accelerate physical confrontation', 'To delay emergency medical response'],
    correctAnswer: 0,
  },
  {
    id: 'q21',
    question: 'What action should a desk officer take if a citizen files a complaint against a fellow police officer?',
    options: ['Refuse to accept the complaint', 'Receive, record, and forward the complaint to the appropriate oversight office', 'Tear up the written complaint', 'Threaten the complainant'],
    correctAnswer: 1,
  },
  {
    id: 'q22',
    question: 'What is the purpose of Body-Worn Cameras (BWCs) during tactical law enforcement operations?',
    options: ['To provide transparent objective records and protect both citizens and officers', 'For entertainment streaming', 'To replace written affidavits completely', 'To eliminate radio communication'],
    correctAnswer: 0,
  },
  {
    id: 'q23',
    question: 'Which doctrine excludes evidence obtained through illegal search or coerced confession from court proceedings?',
    options: ['Fruit of the Poisonous Tree Doctrine', 'Doctrine of Command Responsibility', 'Doctrine of Last Clear Chance', 'Res Judicata Doctrine'],
    correctAnswer: 0,
  },
  {
    id: 'q24',
    question: 'Under the Doctrine of Command Responsibility, a superior officer is held accountable if they:',
    options: ['Knew or should have known about subordinate misconduct and failed to take preventive action', 'Were on mandatory leave abroad', 'Had no administrative oversight authority', 'Commended the unit for routine work'],
    correctAnswer: 0,
  },
  {
    id: 'q25',
    question: 'What is the proper procedure when handling seized illegal drugs during an operation?',
    options: ['Conduct physical inventory and photograph immediately in the presence of required witnesses', 'Store in personal lockers overnight', 'Deliver directly to media outlets', 'Destroy on site without documentation'],
    correctAnswer: 0,
  },
  {
    id: 'q26',
    question: 'Public accountability requires police officers to file their Statement of Assets, Liabilities, and Net Worth (SALN):',
    options: ['Annually', 'Every 5 years', 'Only upon retirement', 'Never'],
    correctAnswer: 0,
  },
  {
    id: 'q27',
    question: 'Which of the following is considered a grave offense resulting in dismissal from police service?',
    options: ['Falsification of official records or extortion', 'Tardy attendance by 5 minutes once', 'Wearing incorrect socks', 'Asking for clarification on orders'],
    correctAnswer: 0,
  },
  {
    id: 'q28',
    question: 'What ethical standard requires police personnel to treat all persons equally regardless of status, gender, or religion?',
    options: ['Impartiality and Non-Discrimination', 'Selectivity', 'Favoritism', 'Arbitrary Discretion'],
    correctAnswer: 0,
  },
  {
    id: 'q29',
    question: 'When responding to domestic violence calls, officers must prioritize:',
    options: ['Victim safety and enforcing protective orders under R.A. 9262', 'Discouraging legal filings', 'Blaming the victim', 'Leaving immediately if married'],
    correctAnswer: 0,
  },
  {
    id: 'q30',
    question: 'What is the primary role of the PNP Human Rights Affairs Office (HRAO)?',
    options: ['Promoting human rights awareness and monitoring compliance in operations', 'Managing logistics budgets', 'Conducting traffic ticketing', 'Managing firearms licensing'],
    correctAnswer: 0,
  },
  {
    id: 'q31',
    question: 'Officers interacting with juveniles in conflict with the law must adhere to:',
    options: ['Juvenile Justice and Welfare Act (R.A. 9344)', 'Adult Criminal Detention Protocols', 'Military Court Rules', 'No specific guidelines'],
    correctAnswer: 0,
  },
  {
    id: 'q32',
    question: 'Which ethical value dictates that an officer must not engage in side businesses that conflict with official duties?',
    options: ['Conflict of Interest Avoidance', 'Profit Seeking', 'Secondary Employment Priority', 'Moonlighting Approval'],
    correctAnswer: 0,
  },
  {
    id: 'q33',
    question: 'What is the expected conduct of police officers on social media platforms?',
    options: ['Uphold dignity, avoid posting political bias or derogatory content', 'Post operational secrets for likes', 'Attack citizens online anonymously', 'Share confidential victim photos'],
    correctAnswer: 0,
  },
  {
    id: 'q34',
    question: 'What is the legal status of an arrest made based on a revoked or expired warrant?',
    options: ['Illegal and invalid', 'Valid under all circumstances', 'Encouraged for speed', 'Automatically ratified'],
    correctAnswer: 0,
  },
  {
    id: 'q35',
    question: 'What should an officer do if ordered by a superior to perform an illegal act?',
    options: ['Refuse the illegal order and report to higher authority', 'Obey without question', 'Execute the act and blame the superior', 'Resign silently'],
    correctAnswer: 0,
  },
  {
    id: 'q36',
    question: 'Which pillar of the Philippine Criminal Justice System includes law enforcement agencies like the PNP?',
    options: ['First Pillar (Law Enforcement)', 'Second Pillar (Prosecution)', 'Third Pillar (Courts)', 'Fourth Pillar (Corrections)'],
    correctAnswer: 0,
  },
  {
    id: 'q37',
    question: 'What is the primary purpose of conducting a daily police briefing (Guard Mounting)?',
    options: ['Inspect personnel, disseminate operational directives, and review ethical reminders', 'Collect personal dues', 'Host social gatherings', 'Cancel patrol shifts'],
    correctAnswer: 0,
  },
  {
    id: 'q38',
    question: 'In disaster response, police officers must adhere to the principles of:',
    options: ['Humanitarian protection and preservation of life', 'Property confiscation', 'Abandoning stations', 'Restricting civilian aid'],
    correctAnswer: 0,
  },
  {
    id: 'q39',
    question: 'What is the maximum period allowed for custodial investigation without filing formal charges for light offenses?',
    options: ['12 hours', '36 hours', '72 hours', '7 days'],
    correctAnswer: 0,
  },
  {
    id: 'q40',
    question: 'Officers utilizing AI tools in decision support must remember that ultimate accountability rests with:',
    options: ['The human police officer making the decision', 'The software developer', 'The computer server', 'The internet provider'],
    correctAnswer: 0,
  },
  {
    id: 'q41',
    question: 'What is the consequence of failing the 50-question PNP Course Final Exam with a score below 80%?',
    options: ['The officer must review the course modules and retake the final exam', 'Permanent ban from training', 'Automatic rank demotion', 'No option to retake'],
    correctAnswer: 0,
  },
  {
    id: 'q42',
    question: 'Ethical communication requires police officers to address members of the public with:',
    options: ['Respect, courtesy, and professional demeanor', 'Hostility and sarcasm', 'Indifference', 'Jargon intended to confuse'],
    correctAnswer: 0,
  },
  {
    id: 'q43',
    question: 'Which document serves as the official record of daily events and incidents in a police station?',
    options: ['Police Blotter', 'Personal Journal', 'Visitor Guestbook', 'Finance Ledger'],
    correctAnswer: 0,
  },
  {
    id: 'q44',
    question: 'What is the primary goal of crime prevention programs in police districts?',
    options: ['Reducing crime opportunities and addressing root causes in communities', 'Increasing jail populations', 'Selling security equipment', 'Maximizing fine collections'],
    correctAnswer: 0,
  },
  {
    id: 'q45',
    question: 'Under R.A. 6713, public officials must respond to letters and requests from the public within how many working days?',
    options: ['15 working days', '30 working days', '60 working days', '90 working days'],
    correctAnswer: 0,
  },
  {
    id: 'q46',
    question: 'What does "Patrol Discipline" require of personnel during mobile or foot patrol duty?',
    options: ['Remaining vigilant, accessible to citizens, and avoiding unapproved personal diversions', 'Sleeping in patrol vehicles', 'Leaving patrol sectors unmonitored', 'Using patrol vehicles for personal errands'],
    correctAnswer: 0,
  },
  {
    id: 'q47',
    question: 'How should police officers handle media inquiries during an active crisis situation?',
    options: ['Designate a designated Public Information Officer (PIO) to provide accurate briefings', 'Allow all officers to give conflicting statements', 'Provide false information to confuse suspects', 'Refuse all public communication indefinitely'],
    correctAnswer: 0,
  },
  {
    id: 'q48',
    question: 'What ethical virtue is demonstrated when an officer admits a mistake and takes steps to rectify it?',
    options: ['Moral courage and accountability', 'Weakness', 'Incompetence', 'Disloyalty'],
    correctAnswer: 0,
  },
  {
    id: 'q49',
    question: 'What certification is awarded to officers who pass the PNP Ethics and Conduct program with >=80% on the final exam?',
    options: ['Official Certificate of Completion in Police Ethics', 'Driver License', 'Firearm License', 'Exemption Certificate'],
    correctAnswer: 0,
  },
  {
    id: 'q50',
    question: 'What is the overall vision of the PNP AI-Powered Training LMS initiative?',
    options: ['To foster highly disciplined, ethical, tech-empowered officers serving the Filipino nation', 'To replace human police officers with robots', 'To reduce training standards', 'To privatize police operations'],
    correctAnswer: 0,
  },
];
